# Generated by Django 6.1.1 on 2026-09-24 15:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FarmPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plot_code",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "farmer_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("village", models.CharField(default="Jhunjhunu", max_length=128)),
                ("district", models.CharField(default="Rajasthan", max_length=128)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                (
                    "area_hectares",
                    models.FloatField(
                        blank=True, help_text="Calculated in UTM projection", null=True
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
